# Site settings
title: Renju thinks
email: ranjani@renjuthinks.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.renjuthinks.com" # the base hostname & protocol for your site
twitter_username: ranjanirs
github_username:  
linkedin_username: sivaranjanirs

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

theme: jekyll-theme-minimal